version: '3'
services:
  web:
    build: .
    container_name: web-server
    restart: always
    volumes:
      - imagedata:/app/static/images/upload
    ports:
      - "8086:8086"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: webserver #Create an initial empty database called webserver
      MYSQL_ROOT_USER: root #root user
      MYSQL_ROOT_PASSWORD: QWEasd123 #root password
      MYSQL_ROOT_HOST: '%' 
      TZ: Asia/Shanghai #time zone
volumes:
  dbdata:
  imagedata: