version: '3'
services:
  #Oracle Service
  appOracleArango:
    image: gvenzl/oracle-xe:21-slim  
    container_name: arango_oracle
    hostname: 127.0.0.1
    environment:
      - POSTGRES_DB=dbtest
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin


    ports:
      - '9091:5432'

    networks:
      - app-network

 

  #MySQL Service
  dbMysqlArango:
    image: mysql:8.0
    restart: always
    container_name: arango_mysql
    tty: true
    environment:
      MYSQL_DATABASE: 'dbdesa'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
  
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
